on: push

jobs:
    secrets:
        runs-on: ubuntu-latest
        steps:
        - run: |
            import os
            print(len(os.get_env('MY_VAR')))
            shell: python
            env:
                MY_VAR: ${{secrets.MY_SECRET}}